# Generated by Django 4.2.5 on 2023-09-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_product_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="size",),
    ]
